In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import myo
from myo.utils import TimeInterval

In [18]:
data = pd.read_csv('./output.csv',header=None)#,names = ['label','time','qa','qb','qc','qd','1','2','3','4','5','6','7','8'])

In [33]:
data.drop(data.columns[[-1,]], axis=1, inplace=True)
print(data)

    0             1       2       3       4       5   6   7   8   9   10  11  \
0    a  1.540139e+09 -0.6119  0.3301 -0.2960  0.6550   2  -3 -11 -42   3   4   
1    a  1.540139e+09 -0.6112  0.3301 -0.2972  0.6551   5   3  -6  41  -9   1   
2    a  1.540139e+09 -0.6111  0.3307 -0.2969  0.6549  -1  -4  -6 -33   8   0   
3    a  1.540139e+09 -0.6103  0.3295 -0.2994  0.6553  -4   3  19  49   1  -3   
4    a  1.540139e+09 -0.6103  0.3294 -0.2994  0.6553  -2  -2  10  71   2  -2   
5    a  1.540139e+09 -0.6110  0.3322 -0.2985  0.6536   1  -2  -9  35 -21   4   
6    a  1.540139e+09 -0.6111  0.3327 -0.3000  0.6526  -1   1   0   2   8  -2   
7    a  1.540139e+09 -0.6115  0.3334 -0.3010  0.6513   1  -2  -7 -22   5   1   
8    a  1.540139e+09 -0.6113  0.3364 -0.3005  0.6502  -2   5   7  28  -4  -3   
9    a  1.540139e+09 -0.6111  0.3373 -0.3009  0.6498  -4  -4  -8 -38   7  -1   
10   a  1.540139e+09 -0.6099  0.3369 -0.3023  0.6505   1 -12 -16  22 -18   5   
11   a  1.540139e+09 -0.6096  0.3378 -0.

In [34]:
data.tail()

0             1       2       3       4       5   6   7   8   9   10  11  \
894  j  1.540139e+09 -0.6205  0.4125 -0.1342  0.6533  -8  -3  -3   5   2  -2   
895  j  1.540139e+09 -0.6205  0.4124 -0.1343  0.6533  -8   0   7   4   3  -1   
896  j  1.540139e+09 -0.6204  0.4128 -0.1349  0.6530  -1  -3  -5  -2   3   2   
897  j  1.540139e+09 -0.6202  0.4128 -0.1352  0.6531  -3  -7  -1  -5  -1   1   
898  j  1.540139e+09 -0.6199  0.4132 -0.1354  0.6531  -1  -3  -2   3  -4  -4   

     12  
894  -1  
895  -4  
896   1  
897  -3  
898  -2

In [35]:
X = data.iloc[:,1:].values
y = data.iloc[:,0].values

In [36]:
print(X)

[[ 1.54013933e+09 -6.11900000e-01  3.30100000e-01 ...  3.00000000e+00
   4.00000000e+00  3.00000000e+00]
 [ 1.54013933e+09 -6.11200000e-01  3.30100000e-01 ... -9.00000000e+00
   1.00000000e+00 -1.00000000e+00]
 [ 1.54013933e+09 -6.11100000e-01  3.30700000e-01 ...  8.00000000e+00
   0.00000000e+00  4.00000000e+00]
 ...
 [ 1.54013942e+09 -6.20400000e-01  4.12800000e-01 ...  3.00000000e+00
   2.00000000e+00  1.00000000e+00]
 [ 1.54013942e+09 -6.20200000e-01  4.12800000e-01 ... -1.00000000e+00
   1.00000000e+00 -3.00000000e+00]
 [ 1.54013942e+09 -6.19900000e-01  4.13200000e-01 ... -4.00000000e+00
  -4.00000000e+00 -2.00000000e+00]]


In [37]:
print(y)

['a' 'a' 'a' 'a' 'a' 'a' 'a' 'a' 'a' 'a' 'a' 'a' 'a' 'a' 'a' 'a' 'a' 'a'
 'a' 'a' 'a' 'a' 'a' 'a' 'a' 'a' 'a' 'a' 'a' 'a' 'a' 'a' 'a' 'a' 'a' 'a'
 'a' 'a' 'a' 'a' 'a' 'a' 'a' 'a' 'a' 'a' 'a' 'a' 'a' 'a' 'a' 'a' 'a' 'a'
 'a' 'a' 'a' 'a' 'a' 'a' 'a' 'a' 'a' 'a' 'a' 'a' 'a' 'a' 'a' 'a' 'a' 'a'
 'a' 'a' 'a' 'a' 'a' 'a' 'a' 'a' 'a' 'a' 'a' 'a' 'a' 'a' 'a' 'a' 'a' 'a'
 'a' 'a' 'a' 'a' 'a' 'a' 'a' 'a' 'a' 'a' 'a' 'a' 'a' 'a' 'a' 'a' 'a' 'a'
 'a' 'a' 'a' 'a' 'a' 'a' 'a' 'a' 'a' 'a' 'a' 'a' 'a' 'a' 'a' 'a' 'a' 'a'
 'a' 'a' 'a' 'a' 'a' 'a' 'a' 'a' 'a' 'a' 'a' 'a' 'a' 'a' 'a' 'a' 'a' 'a'
 'a' 'a' 'a' 'a' 'a' 'a' 'a' 'a' 'a' 'a' 'a' 'a' 'a' 'a' 'a' 'a' 'a' 'a'
 'a' 'a' 'a' 'a' 'a' 'a' 'a' 'a' 'a' 'a' 'a' 'a' 'a' 'a' 'a' 'a' 'a' 'a'
 'a' 'a' 'a' 'a' 'a' 'a' 'a' 'a' 'a' 'a' 'a' 'a' 'a' 'a' 'a' 'a' 'a' 'a'
 'a' 'a' 'a' 'a' 'a' 'b' 'b' 'b' 'b' 'b' 'b' 'b' 'b' 'b' 'b' 'b' 'b' 'b'
 'b' 'b' 'b' 'b' 'b' 'b' 'b' 'b' 'b' 'b' 'b' 'b' 'b' 'b' 'b' 'b' 'b' 'b'
 'b' 'b' 'b' 'b' 'b' 'b' 'b' 'b' 'b' 'b' 'b' 'b' 'b

In [38]:
from sklearn.model_selection import train_test_split  
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.20)  

In [39]:
from sklearn.preprocessing import StandardScaler  
scaler = StandardScaler()  
scaler.fit(X_train)

X_train = scaler.transform(X_train)  
X_test = scaler.transform(X_test) 

In [41]:
from sklearn.neighbors import KNeighborsClassifier  
classifier = KNeighborsClassifier(n_neighbors=5)  
classifier.fit(X_train, y_train)  
y_pred = classifier.predict(X_test)  

In [42]:
from sklearn.metrics import classification_report, confusion_matrix  
print(confusion_matrix(y_test, y_pred))  
print(classification_report(y_test, y_pred))  

[[50  1  0  0]
 [ 1 39  1  0]
 [ 0  1 41  0]
 [ 0  0  3 43]]
              precision    recall  f1-score   support

           a       0.98      0.98      0.98        51
           b       0.95      0.95      0.95        41
           c       0.91      0.98      0.94        42
           j       1.00      0.93      0.97        46

   micro avg       0.96      0.96      0.96       180
   macro avg       0.96      0.96      0.96       180
weighted avg       0.96      0.96      0.96       180



In [ ]:
pred = classifier.predict()